### PR TITLE
Fix : FieldCurrency element overlapping on text

### LINKED ISSUE #474: FieldCurrency start element issue
image

https://demo.start-ui.com/storybook/index.html?path=/docs/form-fieldcurrency--docs#start%20element

### PR DESCRIPTION
**Pull request by ntatoud**
## Describe your changes

The start (and end) elements are overlapping on the FieldCurrency content.
This is because InputCurrency is made with a library other than ChakraUI and the stylings are not working together.
 To fix that, I added a padding to the InputCurrency inside of FieldCurrency if there is an element.

I tested the field with all 4 sizes of input ('xs', 'sm', 'md', lg') and in order it gives : 

image
image
image
image

closes #474
## Checklist
 - [x] I performed a self review of my code
 - [x] I tested the feature or fix on my local environment
 - [x] I ran the `pnpm storybook` command and everything is working

### CODE REVIEW

File: src/components/Form/FieldCurrency/index.tsx [hunk 1]
```diff
@@ -68,8 +68,9 @@ export const FieldCurrency = <
               {...field}
               value={formatValue(field.value, 'from-cents')}
               onChange={(v) => field.onChange(formatValue(v, 'to-cents'))}
+              pl={!!props.startElement ? '2.5em' : ''}
```
Comment (ivan-dalmet) [inline src/components/Form/FieldCurrency/index.tsx:71]:
```suggestion
              pl={!!props.startElement ? '2.5em' : undefined}
```

File: src/components/Form/FieldCurrency/index.tsx [hunk 2]
```diff
@@ -68,8 +68,9 @@ export const FieldCurrency = <
...
+              pr={!!props.endElement ? '2.5em' : ''}
```
Comment (ivan-dalmet) [inline src/components/Form/FieldCurrency/index.tsx:72]:
```suggestion
              pr={!!props.endElement ? '2.5em' : undefined}
```

**Review by ivan-dalmet — CHANGES_REQUESTED** [review]
Replace empty string with undefined, to prevent wrong override 😉

**Review by ivan-dalmet — APPROVED** [review]
